- name: Ensure necessary packages are installed
  become: true
  ansible.builtin.package:
    name:
      - awesome
      - blueman
      - flameshot
      - i3lock
      - lxqt-config
      - lxqt-menu-data
      - lxqt-session
      - network-manager-gnome
      - pavucontrol
      - pasystray
      - playerctl
    state: present
