[colors]
ansi = [
    "#121319",
    "#ffb4ab",
    "#ffa9ff",
    "#bbc5ef",
    "#b5c4ff",
    "#ffa9ff",
    "#bbc5ef",
    "#e3e1ea",
]
background = "#121319"
brights = [
    "#8e909d",
    "#ffb4ab",
    "#ffa9ff",
    "#bbc5ef",
    "#b5c4ff",
    "#ffa9ff",
    "#bbc5ef",
    "#e3e1ea",
]
cursor_bg = "#e3e1ea"
cursor_border = "#e3e1ea"
cursor_fg = "#121319"
foreground = "#e3e1ea"
selection_bg = "#444652"
selection_fg = "#c4c5d4"

[metadata]
name = "Noctalia"
